FROM oven/bun:1.2.18 AS builder
WORKDIR /app

ARG VITE_FLAG_DEVELOPMENT_LOGIN
ENV VITE_FLAG_DEVELOPMENT_LOGIN=${VITE_FLAG_DEVELOPMENT_LOGIN}

COPY frontend/package.json frontend/bun.lock ./
RUN bun install --frozen-lockfile

COPY frontend/. .
RUN bun run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY frontend/nginx.conf.template_local /etc/nginx/templates/default.conf.template

CMD ["nginx", "-g", "daemon off;"]