FROM oven/bun:1.2.18 AS builder
WORKDIR /app

COPY frontend/package.json frontend/bun.lock ./
RUN bun install --frozen-lockfile

COPY frontend/. .
RUN bun run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html

COPY frontend/nginx.conf.template /etc/nginx/templates/default.conf.template

EXPOSE 80
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]